### ISSUE TITLE
Include package versioning

### ISSUE THREAD

**Issue by KacperKubara** [deeplearning-wisc/gradnorm_ood#1]
Hi,
Could you include package versioning for this package? I.e. either `requirements.txt` for pip or `env.yml` for conda? This would be quite helpful to avoid any package versioning errors in the future and help spot some versioning problems if someone uses it with another packages.

**Comment by iurgnauh** [comment]
Thanks for your suggestion! I've added a `requirements.txt`. Feel free to let me know if you have any problem with it!
